name: Deploy
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  trigger_external_test:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow and Wait
        run: |
          echo "Test is running"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: pthapaGuild
          repo: backend-GitHubActions
          github_token: ${{ secrets.E2E_CYPRESS_TESTS }}
          workflow_file_name: deploy.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s

  extract_pull_request_number:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);

  trigger_workflow:
    runs-on: ubuntu-latest
    needs: [extract_pull_request_number]
    steps:
      - name: Dispatch Event
        id: dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.E2E_CYPRESS_TESTS }}
          repository: pthapaGuild/frontend-GitHubActions
          event-type: pr-input
          client-payload: '{"prNumber": "$PULL_NUMBER"}'

      - name: Set Pull Request Number
        run: echo "::set-output name=prNumber::${{ steps.dispatch.outputs.prNumber }}"
