name: Deploy
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  extract_pull_request_number:
    runs-on: ubuntu-latest
    outputs:
      pull_request_number: ${{ steps.extract_pull_request_number.outputs.pull_request_number }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install @actions/core
      - name: Extract Pull Request Number
        id: extract_pull_request_number
        uses: actions/github-script@v6.4.1
        env:
          PULL_NUMBER: ${{ github.event.number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const githubCore = require('@actions/core');
            const prNumber = process.env.PULL_NUMBER.toString();
            githubCore.setOutput('pull_request_number', prNumber);

  # trigger_workflow:
  #   runs-on: ubuntu-latest
  #   needs: [extract_pull_request_number]
  #   steps:
  #     - name: Dispatch Event
  #       id: dispatch
  #       uses: peter-evans/repository-dispatch@v2
  #       with:
  #         token: ${{ secrets.E2E_CYPRESS_TESTS }}
  #         repository: pthapaGuild/frontend-GitHubActions
  #         event-type: pr-input
  #         client-payload: '{"prNumber": "${{ needs.extract_pull_request_number.outputs.pull_request_number }}"}'

  trigger_external_test:
    name: E2E Cypress Tests
    needs: [extract_pull_request_number]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow and Wait
        run: |
          echo "Test is running"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: pthapaGuild
          repo: backend-GitHubActions
          github_token: ${{ secrets.E2E_CYPRESS_TESTS }}
          workflow_file_name: deploy.yml
          client_payload: '{"prNumber": ${{ needs.extract_pull_request_number.outputs.pull_request_number }}}'

  run_deploy_pipeline:
    needs: [extract_pull_request_number, trigger_external_test]
    runs-on: ubuntu-latest
    steps:
      - name: Print Pull Request Number
        run: |
          echo "Pull Request Number: ${{ needs.extract_pull_request_number.outputs.pull_request_number }}"
          echo "Client Payload: ${{ toJson(needs.trigger_external_test.outputs)}}"
