name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run Web App
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow and Wait
        run: |
          echo "Test is running"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: pthapaGuild
          repo: backend-GitHubActions
          github_token: ${{ secrets.E2E_CYPRESS_TESTS }}
          workflow_file_name: deploy.yml
      - name: Deploy Web App
        run: |
          echo "Deploy Web App"
          sleep 10s
