name: Deploy
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  extract_pull_request_number:
    runs-on: ubuntu-latest
    outputs:
      pull_request_number: ${{ steps.extract_pull_request_number.outputs.pull_request_number }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install @actions/core
      - name: Extract Pull Request Number
        id: extract_pull_request_number
        uses: actions/github-script@v6.4.1
        env:
          PULL_NUMBER: ${{ github.event.number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const githubCore = require('@actions/core');
            const prNumber = process.env.PULL_NUMBER.toString();
            githubCore.setOutput('pull_request_number', prNumber);
  # send_pull_request_number:
  #   name: Send Pull Request Number
  #   needs: [extract_pull_request_number]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send Pull Request Number
  #       run: |
  #         echo "Test is running"
  #         sleep 1s
  #     - name: Send repository dispatch event to Repo B
  #       env:
  #         REPO_B_OWNER: pthapaGuild
  #         REPO_B_NAME: backend-GitHubActions
  #         PR_NUMBER: ${{ needs.extract_pull_request_number.outputs.pull_request_number }}
  #         GITHUB_TOKEN: ${{ secrets.E2E_CYPRESS_TESTS }}
  #       run: |
  #         curl -X POST \
  #           -H "Authorization: token $GITHUB_TOKEN" \
  #           -H "Accept: application/vnd.github.everest-preview+json" \
  #           "https://api.github.com/repos/$REPO_B_OWNER/$REPO_B_NAME/dispatches" \
  #           -d '{"event_type": "pr-input", "client_payload": {"prNumber": "'"$PR_NUMBER"'"}}'

  trigger_external_test:
    name: Trigger Cypress Tests
    needs: [extract_pull_request_number]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow and Wait
        id: trigger
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: deploy.yml
          repo: pthapaGuild/backend-GitHubActions
          token: ${{ secrets.E2E_CYPRESS_TESTS }}
          inputs: '{"prNumber": ${{ needs.extract_pull_request_number.outputs.pull_request_number }}}'
      - name: Check Test Workflow Results
        run: |
          if [ "${{ steps.trigger.outputs.workflow-conclusion }}" != "success" ]; then
            echo "Repo B workflow failed"
            exit 1
          fi

  run_deploy_pipeline:
    needs: [extract_pull_request_number, trigger_external_test]
    runs-on: ubuntu-latest
    steps:
      - name: Print Pull Request Number
        run: |
          echo "Pull Request Number: ${{ needs.extract_pull_request_number.outputs.pull_request_number }}"
